//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace Validus.Console.SubscribeSoapService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SubscribeSoap", Namespace="http://talbotuw.com/webservices")]
    public partial class Subscribe : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ValidatePolicyOperationCompleted;
        
        private System.Threading.SendOrPostCallback NeedsPeerReviewOperationCompleted;
        
        private System.Threading.SendOrPostCallback NeedsDouReviewOperationCompleted;
        
        private System.Threading.SendOrPostCallback NeedsInternalWordingsOperationCompleted;
        
        private System.Threading.SendOrPostCallback AreLeadOnPolicyOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPoliciesWithMissingDocumentsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPolicyDetailOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPolicyDetailJSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback PolicySearchOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Subscribe() {
            this.Url = global::Validus.Console.Properties.Settings.Default.Validus_Console_SubscribeSoapService_Subscribe;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ValidatePolicyCompletedEventHandler ValidatePolicyCompleted;
        
        /// <remarks/>
        public event NeedsPeerReviewCompletedEventHandler NeedsPeerReviewCompleted;
        
        /// <remarks/>
        public event NeedsDouReviewCompletedEventHandler NeedsDouReviewCompleted;
        
        /// <remarks/>
        public event NeedsInternalWordingsCompletedEventHandler NeedsInternalWordingsCompleted;
        
        /// <remarks/>
        public event AreLeadOnPolicyCompletedEventHandler AreLeadOnPolicyCompleted;
        
        /// <remarks/>
        public event GetPoliciesWithMissingDocumentsCompletedEventHandler GetPoliciesWithMissingDocumentsCompleted;
        
        /// <remarks/>
        public event GetPolicyDetailCompletedEventHandler GetPolicyDetailCompleted;
        
        /// <remarks/>
        public event GetPolicyDetailJSONCompletedEventHandler GetPolicyDetailJSONCompleted;
        
        /// <remarks/>
        public event PolicySearchCompletedEventHandler PolicySearchCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://talbotuw.com/webservices/ValidatePolicy", RequestNamespace="http://talbotuw.com/webservices", ResponseNamespace="http://talbotuw.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ValidatePolicy(string policyId) {
            object[] results = this.Invoke("ValidatePolicy", new object[] {
                        policyId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ValidatePolicyAsync(string policyId) {
            this.ValidatePolicyAsync(policyId, null);
        }
        
        /// <remarks/>
        public void ValidatePolicyAsync(string policyId, object userState) {
            if ((this.ValidatePolicyOperationCompleted == null)) {
                this.ValidatePolicyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidatePolicyOperationCompleted);
            }
            this.InvokeAsync("ValidatePolicy", new object[] {
                        policyId}, this.ValidatePolicyOperationCompleted, userState);
        }
        
        private void OnValidatePolicyOperationCompleted(object arg) {
            if ((this.ValidatePolicyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidatePolicyCompleted(this, new ValidatePolicyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://talbotuw.com/webservices/NeedsPeerReview", RequestNamespace="http://talbotuw.com/webservices", ResponseNamespace="http://talbotuw.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool NeedsPeerReview(string policyId) {
            object[] results = this.Invoke("NeedsPeerReview", new object[] {
                        policyId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void NeedsPeerReviewAsync(string policyId) {
            this.NeedsPeerReviewAsync(policyId, null);
        }
        
        /// <remarks/>
        public void NeedsPeerReviewAsync(string policyId, object userState) {
            if ((this.NeedsPeerReviewOperationCompleted == null)) {
                this.NeedsPeerReviewOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNeedsPeerReviewOperationCompleted);
            }
            this.InvokeAsync("NeedsPeerReview", new object[] {
                        policyId}, this.NeedsPeerReviewOperationCompleted, userState);
        }
        
        private void OnNeedsPeerReviewOperationCompleted(object arg) {
            if ((this.NeedsPeerReviewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NeedsPeerReviewCompleted(this, new NeedsPeerReviewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://talbotuw.com/webservices/NeedsDouReview", RequestNamespace="http://talbotuw.com/webservices", ResponseNamespace="http://talbotuw.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DouReview NeedsDouReview(string policyId) {
            object[] results = this.Invoke("NeedsDouReview", new object[] {
                        policyId});
            return ((DouReview)(results[0]));
        }
        
        /// <remarks/>
        public void NeedsDouReviewAsync(string policyId) {
            this.NeedsDouReviewAsync(policyId, null);
        }
        
        /// <remarks/>
        public void NeedsDouReviewAsync(string policyId, object userState) {
            if ((this.NeedsDouReviewOperationCompleted == null)) {
                this.NeedsDouReviewOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNeedsDouReviewOperationCompleted);
            }
            this.InvokeAsync("NeedsDouReview", new object[] {
                        policyId}, this.NeedsDouReviewOperationCompleted, userState);
        }
        
        private void OnNeedsDouReviewOperationCompleted(object arg) {
            if ((this.NeedsDouReviewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NeedsDouReviewCompleted(this, new NeedsDouReviewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://talbotuw.com/webservices/NeedsInternalWordings", RequestNamespace="http://talbotuw.com/webservices", ResponseNamespace="http://talbotuw.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool NeedsInternalWordings(string policyId) {
            object[] results = this.Invoke("NeedsInternalWordings", new object[] {
                        policyId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void NeedsInternalWordingsAsync(string policyId) {
            this.NeedsInternalWordingsAsync(policyId, null);
        }
        
        /// <remarks/>
        public void NeedsInternalWordingsAsync(string policyId, object userState) {
            if ((this.NeedsInternalWordingsOperationCompleted == null)) {
                this.NeedsInternalWordingsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNeedsInternalWordingsOperationCompleted);
            }
            this.InvokeAsync("NeedsInternalWordings", new object[] {
                        policyId}, this.NeedsInternalWordingsOperationCompleted, userState);
        }
        
        private void OnNeedsInternalWordingsOperationCompleted(object arg) {
            if ((this.NeedsInternalWordingsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NeedsInternalWordingsCompleted(this, new NeedsInternalWordingsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://talbotuw.com/webservices/AreLeadOnPolicy", RequestNamespace="http://talbotuw.com/webservices", ResponseNamespace="http://talbotuw.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AreLeadOnPolicy(string policyId) {
            object[] results = this.Invoke("AreLeadOnPolicy", new object[] {
                        policyId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AreLeadOnPolicyAsync(string policyId) {
            this.AreLeadOnPolicyAsync(policyId, null);
        }
        
        /// <remarks/>
        public void AreLeadOnPolicyAsync(string policyId, object userState) {
            if ((this.AreLeadOnPolicyOperationCompleted == null)) {
                this.AreLeadOnPolicyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAreLeadOnPolicyOperationCompleted);
            }
            this.InvokeAsync("AreLeadOnPolicy", new object[] {
                        policyId}, this.AreLeadOnPolicyOperationCompleted, userState);
        }
        
        private void OnAreLeadOnPolicyOperationCompleted(object arg) {
            if ((this.AreLeadOnPolicyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AreLeadOnPolicyCompleted(this, new AreLeadOnPolicyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://talbotuw.com/webservices/GetPoliciesWithMissingDocuments", RequestNamespace="http://talbotuw.com/webservices", ResponseNamespace="http://talbotuw.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Policy[] GetPoliciesWithMissingDocuments() {
            object[] results = this.Invoke("GetPoliciesWithMissingDocuments", new object[0]);
            return ((Policy[])(results[0]));
        }
        
        /// <remarks/>
        public void GetPoliciesWithMissingDocumentsAsync() {
            this.GetPoliciesWithMissingDocumentsAsync(null);
        }
        
        /// <remarks/>
        public void GetPoliciesWithMissingDocumentsAsync(object userState) {
            if ((this.GetPoliciesWithMissingDocumentsOperationCompleted == null)) {
                this.GetPoliciesWithMissingDocumentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPoliciesWithMissingDocumentsOperationCompleted);
            }
            this.InvokeAsync("GetPoliciesWithMissingDocuments", new object[0], this.GetPoliciesWithMissingDocumentsOperationCompleted, userState);
        }
        
        private void OnGetPoliciesWithMissingDocumentsOperationCompleted(object arg) {
            if ((this.GetPoliciesWithMissingDocumentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPoliciesWithMissingDocumentsCompleted(this, new GetPoliciesWithMissingDocumentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://talbotuw.com/webservices/GetPolicyDetail", RequestNamespace="http://talbotuw.com/webservices", ResponseNamespace="http://talbotuw.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Policy GetPolicyDetail(string policyId) {
            object[] results = this.Invoke("GetPolicyDetail", new object[] {
                        policyId});
            return ((Policy)(results[0]));
        }
        
        /// <remarks/>
        public void GetPolicyDetailAsync(string policyId) {
            this.GetPolicyDetailAsync(policyId, null);
        }
        
        /// <remarks/>
        public void GetPolicyDetailAsync(string policyId, object userState) {
            if ((this.GetPolicyDetailOperationCompleted == null)) {
                this.GetPolicyDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPolicyDetailOperationCompleted);
            }
            this.InvokeAsync("GetPolicyDetail", new object[] {
                        policyId}, this.GetPolicyDetailOperationCompleted, userState);
        }
        
        private void OnGetPolicyDetailOperationCompleted(object arg) {
            if ((this.GetPolicyDetailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPolicyDetailCompleted(this, new GetPolicyDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://talbotuw.com/webservices/GetPolicyDetailJSON", RequestNamespace="http://talbotuw.com/webservices", ResponseNamespace="http://talbotuw.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetPolicyDetailJSON(string policyId) {
            object[] results = this.Invoke("GetPolicyDetailJSON", new object[] {
                        policyId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetPolicyDetailJSONAsync(string policyId) {
            this.GetPolicyDetailJSONAsync(policyId, null);
        }
        
        /// <remarks/>
        public void GetPolicyDetailJSONAsync(string policyId, object userState) {
            if ((this.GetPolicyDetailJSONOperationCompleted == null)) {
                this.GetPolicyDetailJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPolicyDetailJSONOperationCompleted);
            }
            this.InvokeAsync("GetPolicyDetailJSON", new object[] {
                        policyId}, this.GetPolicyDetailJSONOperationCompleted, userState);
        }
        
        private void OnGetPolicyDetailJSONOperationCompleted(object arg) {
            if ((this.GetPolicyDetailJSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPolicyDetailJSONCompleted(this, new GetPolicyDetailJSONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://talbotuw.com/webservices/PolicySearch", RequestNamespace="http://talbotuw.com/webservices", ResponseNamespace="http://talbotuw.com/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Policy[] PolicySearch(Policy searchCriteria) {
            object[] results = this.Invoke("PolicySearch", new object[] {
                        searchCriteria});
            return ((Policy[])(results[0]));
        }
        
        /// <remarks/>
        public void PolicySearchAsync(Policy searchCriteria) {
            this.PolicySearchAsync(searchCriteria, null);
        }
        
        /// <remarks/>
        public void PolicySearchAsync(Policy searchCriteria, object userState) {
            if ((this.PolicySearchOperationCompleted == null)) {
                this.PolicySearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPolicySearchOperationCompleted);
            }
            this.InvokeAsync("PolicySearch", new object[] {
                        searchCriteria}, this.PolicySearchOperationCompleted, userState);
        }
        
        private void OnPolicySearchOperationCompleted(object arg) {
            if ((this.PolicySearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PolicySearchCompleted(this, new PolicySearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://talbotuw.com/webservices")]
    public partial class DouReview {
        
        private string policyIdField;
        
        private bool reviewRequiredField;
        
        private bool limitExceptionField;
        
        private bool netLimitExceptionField;
        
        private bool policyTypeExceptionField;
        
        private bool riskCodeExceptionField;
        
        private bool percentExceptionField;
        
        private bool premiumExceptionField;
        
        private bool accountYearExceptionField;
        
        private bool longRiskExceptionField;
        
        private bool groupOverLimitField;
        
        private bool groupPremiumExceptionField;
        
        /// <remarks/>
        public string PolicyId {
            get {
                return this.policyIdField;
            }
            set {
                this.policyIdField = value;
            }
        }
        
        /// <remarks/>
        public bool ReviewRequired {
            get {
                return this.reviewRequiredField;
            }
            set {
                this.reviewRequiredField = value;
            }
        }
        
        /// <remarks/>
        public bool LimitException {
            get {
                return this.limitExceptionField;
            }
            set {
                this.limitExceptionField = value;
            }
        }
        
        /// <remarks/>
        public bool NetLimitException {
            get {
                return this.netLimitExceptionField;
            }
            set {
                this.netLimitExceptionField = value;
            }
        }
        
        /// <remarks/>
        public bool PolicyTypeException {
            get {
                return this.policyTypeExceptionField;
            }
            set {
                this.policyTypeExceptionField = value;
            }
        }
        
        /// <remarks/>
        public bool RiskCodeException {
            get {
                return this.riskCodeExceptionField;
            }
            set {
                this.riskCodeExceptionField = value;
            }
        }
        
        /// <remarks/>
        public bool PercentException {
            get {
                return this.percentExceptionField;
            }
            set {
                this.percentExceptionField = value;
            }
        }
        
        /// <remarks/>
        public bool PremiumException {
            get {
                return this.premiumExceptionField;
            }
            set {
                this.premiumExceptionField = value;
            }
        }
        
        /// <remarks/>
        public bool AccountYearException {
            get {
                return this.accountYearExceptionField;
            }
            set {
                this.accountYearExceptionField = value;
            }
        }
        
        /// <remarks/>
        public bool LongRiskException {
            get {
                return this.longRiskExceptionField;
            }
            set {
                this.longRiskExceptionField = value;
            }
        }
        
        /// <remarks/>
        public bool GroupOverLimit {
            get {
                return this.groupOverLimitField;
            }
            set {
                this.groupOverLimitField = value;
            }
        }
        
        /// <remarks/>
        public bool GroupPremiumException {
            get {
                return this.groupPremiumExceptionField;
            }
            set {
                this.groupPremiumExceptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://talbotuw.com/webservices")]
    public partial class Policy {
        
        private string policyIdField;
        
        private string insuredField;
        
        private string underwriterPseudonymField;
        
        private string classOfBusinessField;
        
        private string accountYearField;
        
        private string inceptionDateField;
        
        private string statusField;
        
        private string entryStatusField;
        
        private string brokerPseudonymField;
        
        private string writtenDateField;
        
        private string leaderField;
        
        private string overseasOfficeCodeField;
        
        private string divisionCodeField;
        
        private string businessPlanField;
        
        /// <remarks/>
        public string PolicyId {
            get {
                return this.policyIdField;
            }
            set {
                this.policyIdField = value;
            }
        }
        
        /// <remarks/>
        public string Insured {
            get {
                return this.insuredField;
            }
            set {
                this.insuredField = value;
            }
        }
        
        /// <remarks/>
        public string UnderwriterPseudonym {
            get {
                return this.underwriterPseudonymField;
            }
            set {
                this.underwriterPseudonymField = value;
            }
        }
        
        /// <remarks/>
        public string ClassOfBusiness {
            get {
                return this.classOfBusinessField;
            }
            set {
                this.classOfBusinessField = value;
            }
        }
        
        /// <remarks/>
        public string AccountYear {
            get {
                return this.accountYearField;
            }
            set {
                this.accountYearField = value;
            }
        }
        
        /// <remarks/>
        public string InceptionDate {
            get {
                return this.inceptionDateField;
            }
            set {
                this.inceptionDateField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string EntryStatus {
            get {
                return this.entryStatusField;
            }
            set {
                this.entryStatusField = value;
            }
        }
        
        /// <remarks/>
        public string BrokerPseudonym {
            get {
                return this.brokerPseudonymField;
            }
            set {
                this.brokerPseudonymField = value;
            }
        }
        
        /// <remarks/>
        public string WrittenDate {
            get {
                return this.writtenDateField;
            }
            set {
                this.writtenDateField = value;
            }
        }
        
        /// <remarks/>
        public string Leader {
            get {
                return this.leaderField;
            }
            set {
                this.leaderField = value;
            }
        }
        
        /// <remarks/>
        public string OverseasOfficeCode {
            get {
                return this.overseasOfficeCodeField;
            }
            set {
                this.overseasOfficeCodeField = value;
            }
        }
        
        /// <remarks/>
        public string DivisionCode {
            get {
                return this.divisionCodeField;
            }
            set {
                this.divisionCodeField = value;
            }
        }
        
        /// <remarks/>
        public string BusinessPlan {
            get {
                return this.businessPlanField;
            }
            set {
                this.businessPlanField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ValidatePolicyCompletedEventHandler(object sender, ValidatePolicyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidatePolicyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidatePolicyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void NeedsPeerReviewCompletedEventHandler(object sender, NeedsPeerReviewCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NeedsPeerReviewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NeedsPeerReviewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void NeedsDouReviewCompletedEventHandler(object sender, NeedsDouReviewCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NeedsDouReviewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NeedsDouReviewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DouReview Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DouReview)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void NeedsInternalWordingsCompletedEventHandler(object sender, NeedsInternalWordingsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NeedsInternalWordingsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NeedsInternalWordingsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void AreLeadOnPolicyCompletedEventHandler(object sender, AreLeadOnPolicyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AreLeadOnPolicyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AreLeadOnPolicyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetPoliciesWithMissingDocumentsCompletedEventHandler(object sender, GetPoliciesWithMissingDocumentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPoliciesWithMissingDocumentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPoliciesWithMissingDocumentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Policy[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Policy[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetPolicyDetailCompletedEventHandler(object sender, GetPolicyDetailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPolicyDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPolicyDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Policy Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Policy)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetPolicyDetailJSONCompletedEventHandler(object sender, GetPolicyDetailJSONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPolicyDetailJSONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPolicyDetailJSONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void PolicySearchCompletedEventHandler(object sender, PolicySearchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PolicySearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PolicySearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Policy[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Policy[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591