// <auto-generated />
namespace Validus.Console.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class R1_Patch1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(R1_Patch1));
        
        string IMigrationMetadata.Id
        {
            get { return "201308071337468_R1_Patch1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
