// <auto-generated />
namespace Validus.Console.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class R2_201309_2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(R2_201309_2));
        
        string IMigrationMetadata.Id
        {
            get { return "201309021559043_R2_201309_2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
