// <auto-generated />
namespace Validus.Console.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class R3_201310_7 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(R3_201310_7));
        
        string IMigrationMetadata.Id
        {
            get { return "201310081437107_R3_201310_7"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
