//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Validus.Console.BrokerService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BrokerMeasures", Namespace="http://schemas.datacontract.org/2004/07/Validus.Services.DataContract.ASWarehouse" +
        "")]
    [System.SerializableAttribute()]
    public partial class BrokerMeasures : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrokerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> GrossIncurredLossRatioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> GrossSyndicateEPIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> SyndicateEPIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> USMPremiumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Broker {
            get {
                return this.BrokerField;
            }
            set {
                if ((object.ReferenceEquals(this.BrokerField, value) != true)) {
                    this.BrokerField = value;
                    this.RaisePropertyChanged("Broker");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> GrossIncurredLossRatio {
            get {
                return this.GrossIncurredLossRatioField;
            }
            set {
                if ((this.GrossIncurredLossRatioField.Equals(value) != true)) {
                    this.GrossIncurredLossRatioField = value;
                    this.RaisePropertyChanged("GrossIncurredLossRatio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> GrossSyndicateEPI {
            get {
                return this.GrossSyndicateEPIField;
            }
            set {
                if ((this.GrossSyndicateEPIField.Equals(value) != true)) {
                    this.GrossSyndicateEPIField = value;
                    this.RaisePropertyChanged("GrossSyndicateEPI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> SyndicateEPI {
            get {
                return this.SyndicateEPIField;
            }
            set {
                if ((this.SyndicateEPIField.Equals(value) != true)) {
                    this.SyndicateEPIField = value;
                    this.RaisePropertyChanged("SyndicateEPI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> USMPremium {
            get {
                return this.USMPremiumField;
            }
            set {
                if ((this.USMPremiumField.Equals(value) != true)) {
                    this.USMPremiumField = value;
                    this.RaisePropertyChanged("USMPremium");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BrokerSummary", Namespace="http://schemas.datacontract.org/2004/07/Validus.Services.DataContract.ASWarehouse" +
        "")]
    [System.SerializableAttribute()]
    public partial class BrokerSummary : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrokerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrokerRatingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrokerScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreditLimitField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Broker {
            get {
                return this.BrokerField;
            }
            set {
                if ((object.ReferenceEquals(this.BrokerField, value) != true)) {
                    this.BrokerField = value;
                    this.RaisePropertyChanged("Broker");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BrokerRating {
            get {
                return this.BrokerRatingField;
            }
            set {
                if ((object.ReferenceEquals(this.BrokerRatingField, value) != true)) {
                    this.BrokerRatingField = value;
                    this.RaisePropertyChanged("BrokerRating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BrokerScore {
            get {
                return this.BrokerScoreField;
            }
            set {
                if ((object.ReferenceEquals(this.BrokerScoreField, value) != true)) {
                    this.BrokerScoreField = value;
                    this.RaisePropertyChanged("BrokerScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreditLimit {
            get {
                return this.CreditLimitField;
            }
            set {
                if ((object.ReferenceEquals(this.CreditLimitField, value) != true)) {
                    this.CreditLimitField = value;
                    this.RaisePropertyChanged("CreditLimit");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BrokerDetails", Namespace="http://schemas.datacontract.org/2004/07/Validus.Services.DataContract.ASWarehouse" +
        "")]
    [System.SerializableAttribute()]
    public partial class BrokerDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrokerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DevelopmentMonthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DevelopmentQuarterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DevelopmentYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> GrossIncurredClaimsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> GrossIncurredLossRatioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> GrossSyndicateEPIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> NewClaimCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> SyndicateEPIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> TechnicalPremiumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> USMPremiumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountYear {
            get {
                return this.AccountYearField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountYearField, value) != true)) {
                    this.AccountYearField = value;
                    this.RaisePropertyChanged("AccountYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Broker {
            get {
                return this.BrokerField;
            }
            set {
                if ((object.ReferenceEquals(this.BrokerField, value) != true)) {
                    this.BrokerField = value;
                    this.RaisePropertyChanged("Broker");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COB {
            get {
                return this.COBField;
            }
            set {
                if ((object.ReferenceEquals(this.COBField, value) != true)) {
                    this.COBField = value;
                    this.RaisePropertyChanged("COB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DevelopmentMonth {
            get {
                return this.DevelopmentMonthField;
            }
            set {
                if ((object.ReferenceEquals(this.DevelopmentMonthField, value) != true)) {
                    this.DevelopmentMonthField = value;
                    this.RaisePropertyChanged("DevelopmentMonth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DevelopmentQuarter {
            get {
                return this.DevelopmentQuarterField;
            }
            set {
                if ((object.ReferenceEquals(this.DevelopmentQuarterField, value) != true)) {
                    this.DevelopmentQuarterField = value;
                    this.RaisePropertyChanged("DevelopmentQuarter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DevelopmentYear {
            get {
                return this.DevelopmentYearField;
            }
            set {
                if ((object.ReferenceEquals(this.DevelopmentYearField, value) != true)) {
                    this.DevelopmentYearField = value;
                    this.RaisePropertyChanged("DevelopmentYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> GrossIncurredClaims {
            get {
                return this.GrossIncurredClaimsField;
            }
            set {
                if ((this.GrossIncurredClaimsField.Equals(value) != true)) {
                    this.GrossIncurredClaimsField = value;
                    this.RaisePropertyChanged("GrossIncurredClaims");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> GrossIncurredLossRatio {
            get {
                return this.GrossIncurredLossRatioField;
            }
            set {
                if ((this.GrossIncurredLossRatioField.Equals(value) != true)) {
                    this.GrossIncurredLossRatioField = value;
                    this.RaisePropertyChanged("GrossIncurredLossRatio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> GrossSyndicateEPI {
            get {
                return this.GrossSyndicateEPIField;
            }
            set {
                if ((this.GrossSyndicateEPIField.Equals(value) != true)) {
                    this.GrossSyndicateEPIField = value;
                    this.RaisePropertyChanged("GrossSyndicateEPI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> NewClaimCount {
            get {
                return this.NewClaimCountField;
            }
            set {
                if ((this.NewClaimCountField.Equals(value) != true)) {
                    this.NewClaimCountField = value;
                    this.RaisePropertyChanged("NewClaimCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> SyndicateEPI {
            get {
                return this.SyndicateEPIField;
            }
            set {
                if ((this.SyndicateEPIField.Equals(value) != true)) {
                    this.SyndicateEPIField = value;
                    this.RaisePropertyChanged("SyndicateEPI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> TechnicalPremium {
            get {
                return this.TechnicalPremiumField;
            }
            set {
                if ((this.TechnicalPremiumField.Equals(value) != true)) {
                    this.TechnicalPremiumField = value;
                    this.RaisePropertyChanged("TechnicalPremium");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> USMPremium {
            get {
                return this.USMPremiumField;
            }
            set {
                if ((this.USMPremiumField.Equals(value) != true)) {
                    this.USMPremiumField = value;
                    this.RaisePropertyChanged("USMPremium");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BrokerDevelopmentStatistic", Namespace="http://schemas.datacontract.org/2004/07/Validus.Services.DataContract.ASWarehouse" +
        "")]
    [System.SerializableAttribute()]
    public partial class BrokerDevelopmentStatistic : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrokerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DevelopmentMonthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DevelopmentQuarterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DevelopmentYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> GrossIncurredClaimsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> GrossIncurredLossRatioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> GrossSyndicateEPIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> LossRatioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> NewClaimCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> SyndicateEPIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> SyndicateGrossOutstandingClaimField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> SyndicateGrossPaidClaimField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> TechnicalPremiumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> USMPremiumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountYear {
            get {
                return this.AccountYearField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountYearField, value) != true)) {
                    this.AccountYearField = value;
                    this.RaisePropertyChanged("AccountYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Broker {
            get {
                return this.BrokerField;
            }
            set {
                if ((object.ReferenceEquals(this.BrokerField, value) != true)) {
                    this.BrokerField = value;
                    this.RaisePropertyChanged("Broker");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DevelopmentMonth {
            get {
                return this.DevelopmentMonthField;
            }
            set {
                if ((object.ReferenceEquals(this.DevelopmentMonthField, value) != true)) {
                    this.DevelopmentMonthField = value;
                    this.RaisePropertyChanged("DevelopmentMonth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DevelopmentQuarter {
            get {
                return this.DevelopmentQuarterField;
            }
            set {
                if ((object.ReferenceEquals(this.DevelopmentQuarterField, value) != true)) {
                    this.DevelopmentQuarterField = value;
                    this.RaisePropertyChanged("DevelopmentQuarter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DevelopmentYear {
            get {
                return this.DevelopmentYearField;
            }
            set {
                if ((object.ReferenceEquals(this.DevelopmentYearField, value) != true)) {
                    this.DevelopmentYearField = value;
                    this.RaisePropertyChanged("DevelopmentYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> GrossIncurredClaims {
            get {
                return this.GrossIncurredClaimsField;
            }
            set {
                if ((this.GrossIncurredClaimsField.Equals(value) != true)) {
                    this.GrossIncurredClaimsField = value;
                    this.RaisePropertyChanged("GrossIncurredClaims");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> GrossIncurredLossRatio {
            get {
                return this.GrossIncurredLossRatioField;
            }
            set {
                if ((this.GrossIncurredLossRatioField.Equals(value) != true)) {
                    this.GrossIncurredLossRatioField = value;
                    this.RaisePropertyChanged("GrossIncurredLossRatio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> GrossSyndicateEPI {
            get {
                return this.GrossSyndicateEPIField;
            }
            set {
                if ((this.GrossSyndicateEPIField.Equals(value) != true)) {
                    this.GrossSyndicateEPIField = value;
                    this.RaisePropertyChanged("GrossSyndicateEPI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> LossRatio {
            get {
                return this.LossRatioField;
            }
            set {
                if ((this.LossRatioField.Equals(value) != true)) {
                    this.LossRatioField = value;
                    this.RaisePropertyChanged("LossRatio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> NewClaimCount {
            get {
                return this.NewClaimCountField;
            }
            set {
                if ((this.NewClaimCountField.Equals(value) != true)) {
                    this.NewClaimCountField = value;
                    this.RaisePropertyChanged("NewClaimCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> SyndicateEPI {
            get {
                return this.SyndicateEPIField;
            }
            set {
                if ((this.SyndicateEPIField.Equals(value) != true)) {
                    this.SyndicateEPIField = value;
                    this.RaisePropertyChanged("SyndicateEPI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> SyndicateGrossOutstandingClaim {
            get {
                return this.SyndicateGrossOutstandingClaimField;
            }
            set {
                if ((this.SyndicateGrossOutstandingClaimField.Equals(value) != true)) {
                    this.SyndicateGrossOutstandingClaimField = value;
                    this.RaisePropertyChanged("SyndicateGrossOutstandingClaim");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> SyndicateGrossPaidClaim {
            get {
                return this.SyndicateGrossPaidClaimField;
            }
            set {
                if ((this.SyndicateGrossPaidClaimField.Equals(value) != true)) {
                    this.SyndicateGrossPaidClaimField = value;
                    this.RaisePropertyChanged("SyndicateGrossPaidClaim");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> TechnicalPremium {
            get {
                return this.TechnicalPremiumField;
            }
            set {
                if ((this.TechnicalPremiumField.Equals(value) != true)) {
                    this.TechnicalPremiumField = value;
                    this.RaisePropertyChanged("TechnicalPremium");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> USMPremium {
            get {
                return this.USMPremiumField;
            }
            set {
                if ((this.USMPremiumField.Equals(value) != true)) {
                    this.USMPremiumField = value;
                    this.RaisePropertyChanged("USMPremium");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BrokerService.IBrokerService")]
    public interface IBrokerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrokerService/GetBrokerMeasuresById", ReplyAction="http://tempuri.org/IBrokerService/GetBrokerMeasuresByIdResponse")]
        Validus.Console.BrokerService.BrokerMeasures GetBrokerMeasuresById(string brokerCd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrokerService/GetBrokerMeasuresById", ReplyAction="http://tempuri.org/IBrokerService/GetBrokerMeasuresByIdResponse")]
        System.Threading.Tasks.Task<Validus.Console.BrokerService.BrokerMeasures> GetBrokerMeasuresByIdAsync(string brokerCd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrokerService/GetBrokerSummaryById", ReplyAction="http://tempuri.org/IBrokerService/GetBrokerSummaryByIdResponse")]
        Validus.Console.BrokerService.BrokerSummary GetBrokerSummaryById(string brokerCd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrokerService/GetBrokerSummaryById", ReplyAction="http://tempuri.org/IBrokerService/GetBrokerSummaryByIdResponse")]
        System.Threading.Tasks.Task<Validus.Console.BrokerService.BrokerSummary> GetBrokerSummaryByIdAsync(string brokerCd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrokerService/ListBrokerMeasures", ReplyAction="http://tempuri.org/IBrokerService/ListBrokerMeasuresResponse")]
        System.Collections.Generic.List<Validus.Console.BrokerService.BrokerMeasures> ListBrokerMeasures();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrokerService/ListBrokerMeasures", ReplyAction="http://tempuri.org/IBrokerService/ListBrokerMeasuresResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Validus.Console.BrokerService.BrokerMeasures>> ListBrokerMeasuresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrokerService/GetBrokerDetailsById", ReplyAction="http://tempuri.org/IBrokerService/GetBrokerDetailsByIdResponse")]
        System.Collections.Generic.List<Validus.Console.BrokerService.BrokerDetails> GetBrokerDetailsById(string brokerCd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrokerService/GetBrokerDetailsById", ReplyAction="http://tempuri.org/IBrokerService/GetBrokerDetailsByIdResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Validus.Console.BrokerService.BrokerDetails>> GetBrokerDetailsByIdAsync(string brokerCd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrokerService/GetBrokerDevelopmentStatsById", ReplyAction="http://tempuri.org/IBrokerService/GetBrokerDevelopmentStatsByIdResponse")]
        System.Collections.Generic.List<Validus.Console.BrokerService.BrokerDevelopmentStatistic> GetBrokerDevelopmentStatsById(string brokerCd, string cobs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrokerService/GetBrokerDevelopmentStatsById", ReplyAction="http://tempuri.org/IBrokerService/GetBrokerDevelopmentStatsByIdResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Validus.Console.BrokerService.BrokerDevelopmentStatistic>> GetBrokerDevelopmentStatsByIdAsync(string brokerCd, string cobs);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBrokerServiceChannel : Validus.Console.BrokerService.IBrokerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BrokerServiceClient : System.ServiceModel.ClientBase<Validus.Console.BrokerService.IBrokerService>, Validus.Console.BrokerService.IBrokerService {
        
        public BrokerServiceClient() {
        }
        
        public BrokerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BrokerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BrokerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BrokerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Validus.Console.BrokerService.BrokerMeasures GetBrokerMeasuresById(string brokerCd) {
            return base.Channel.GetBrokerMeasuresById(brokerCd);
        }
        
        public System.Threading.Tasks.Task<Validus.Console.BrokerService.BrokerMeasures> GetBrokerMeasuresByIdAsync(string brokerCd) {
            return base.Channel.GetBrokerMeasuresByIdAsync(brokerCd);
        }
        
        public Validus.Console.BrokerService.BrokerSummary GetBrokerSummaryById(string brokerCd) {
            return base.Channel.GetBrokerSummaryById(brokerCd);
        }
        
        public System.Threading.Tasks.Task<Validus.Console.BrokerService.BrokerSummary> GetBrokerSummaryByIdAsync(string brokerCd) {
            return base.Channel.GetBrokerSummaryByIdAsync(brokerCd);
        }
        
        public System.Collections.Generic.List<Validus.Console.BrokerService.BrokerMeasures> ListBrokerMeasures() {
            return base.Channel.ListBrokerMeasures();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Validus.Console.BrokerService.BrokerMeasures>> ListBrokerMeasuresAsync() {
            return base.Channel.ListBrokerMeasuresAsync();
        }
        
        public System.Collections.Generic.List<Validus.Console.BrokerService.BrokerDetails> GetBrokerDetailsById(string brokerCd) {
            return base.Channel.GetBrokerDetailsById(brokerCd);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Validus.Console.BrokerService.BrokerDetails>> GetBrokerDetailsByIdAsync(string brokerCd) {
            return base.Channel.GetBrokerDetailsByIdAsync(brokerCd);
        }
        
        public System.Collections.Generic.List<Validus.Console.BrokerService.BrokerDevelopmentStatistic> GetBrokerDevelopmentStatsById(string brokerCd, string cobs) {
            return base.Channel.GetBrokerDevelopmentStatsById(brokerCd, cobs);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Validus.Console.BrokerService.BrokerDevelopmentStatistic>> GetBrokerDevelopmentStatsByIdAsync(string brokerCd, string cobs) {
            return base.Channel.GetBrokerDevelopmentStatsByIdAsync(brokerCd, cobs);
        }
    }
}
