//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Validus.Console.SubscribeService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Policy", Namespace="Subscribe.Service.DataContract")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Validus.Console.SubscribeService.PolicyContract))]
    public partial class Policy : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string UnitPsuField;
        
        private string PolTyField;
        
        private string EntStField;
        
        private string InsdNmField;
        
        private int InsdIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PolDscField;
        
        private string UwrField;
        
        private string DOMField;
        
        private int BkrSeqIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CtcNmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IncpDtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExpyDtField;
        
        private string AccYrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SettDueDtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> BrokerageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeclineReasonField;
        
        private string COBField;
        
        private string MOAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NonLonBkrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrigOffField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FacyPolIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RenPolIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PolIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LmtCcyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> LmtAmtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExsCcyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ExsAmtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BindStField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PctgAmtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PricingCcyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TechPrmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> BenchPrmField;
        
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> TimeStampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BkrPsuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BkrNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TechPmTyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LdrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LdrNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FacyDscField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string UnitPsu {
            get {
                return this.UnitPsuField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitPsuField, value) != true)) {
                    this.UnitPsuField = value;
                    this.RaisePropertyChanged("UnitPsu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string PolTy {
            get {
                return this.PolTyField;
            }
            set {
                if ((object.ReferenceEquals(this.PolTyField, value) != true)) {
                    this.PolTyField = value;
                    this.RaisePropertyChanged("PolTy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string EntSt {
            get {
                return this.EntStField;
            }
            set {
                if ((object.ReferenceEquals(this.EntStField, value) != true)) {
                    this.EntStField = value;
                    this.RaisePropertyChanged("EntSt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public string InsdNm {
            get {
                return this.InsdNmField;
            }
            set {
                if ((object.ReferenceEquals(this.InsdNmField, value) != true)) {
                    this.InsdNmField = value;
                    this.RaisePropertyChanged("InsdNm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int InsdId {
            get {
                return this.InsdIdField;
            }
            set {
                if ((this.InsdIdField.Equals(value) != true)) {
                    this.InsdIdField = value;
                    this.RaisePropertyChanged("InsdId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string PolDsc {
            get {
                return this.PolDscField;
            }
            set {
                if ((object.ReferenceEquals(this.PolDscField, value) != true)) {
                    this.PolDscField = value;
                    this.RaisePropertyChanged("PolDsc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=6)]
        public string Uwr {
            get {
                return this.UwrField;
            }
            set {
                if ((object.ReferenceEquals(this.UwrField, value) != true)) {
                    this.UwrField = value;
                    this.RaisePropertyChanged("Uwr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=7)]
        public string DOM {
            get {
                return this.DOMField;
            }
            set {
                if ((object.ReferenceEquals(this.DOMField, value) != true)) {
                    this.DOMField = value;
                    this.RaisePropertyChanged("DOM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int BkrSeqId {
            get {
                return this.BkrSeqIdField;
            }
            set {
                if ((this.BkrSeqIdField.Equals(value) != true)) {
                    this.BkrSeqIdField = value;
                    this.RaisePropertyChanged("BkrSeqId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string CtcNm {
            get {
                return this.CtcNmField;
            }
            set {
                if ((object.ReferenceEquals(this.CtcNmField, value) != true)) {
                    this.CtcNmField = value;
                    this.RaisePropertyChanged("CtcNm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string IncpDt {
            get {
                return this.IncpDtField;
            }
            set {
                if ((object.ReferenceEquals(this.IncpDtField, value) != true)) {
                    this.IncpDtField = value;
                    this.RaisePropertyChanged("IncpDt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string ExpyDt {
            get {
                return this.ExpyDtField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpyDtField, value) != true)) {
                    this.ExpyDtField = value;
                    this.RaisePropertyChanged("ExpyDt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public string AccYr {
            get {
                return this.AccYrField;
            }
            set {
                if ((object.ReferenceEquals(this.AccYrField, value) != true)) {
                    this.AccYrField = value;
                    this.RaisePropertyChanged("AccYr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public string SettDueDt {
            get {
                return this.SettDueDtField;
            }
            set {
                if ((object.ReferenceEquals(this.SettDueDtField, value) != true)) {
                    this.SettDueDtField = value;
                    this.RaisePropertyChanged("SettDueDt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public System.Nullable<decimal> Brokerage {
            get {
                return this.BrokerageField;
            }
            set {
                if ((this.BrokerageField.Equals(value) != true)) {
                    this.BrokerageField = value;
                    this.RaisePropertyChanged("Brokerage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public string DeclineReason {
            get {
                return this.DeclineReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.DeclineReasonField, value) != true)) {
                    this.DeclineReasonField = value;
                    this.RaisePropertyChanged("DeclineReason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=16)]
        public string COB {
            get {
                return this.COBField;
            }
            set {
                if ((object.ReferenceEquals(this.COBField, value) != true)) {
                    this.COBField = value;
                    this.RaisePropertyChanged("COB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=17)]
        public string MOA {
            get {
                return this.MOAField;
            }
            set {
                if ((object.ReferenceEquals(this.MOAField, value) != true)) {
                    this.MOAField = value;
                    this.RaisePropertyChanged("MOA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        public string NonLonBkr {
            get {
                return this.NonLonBkrField;
            }
            set {
                if ((object.ReferenceEquals(this.NonLonBkrField, value) != true)) {
                    this.NonLonBkrField = value;
                    this.RaisePropertyChanged("NonLonBkr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=19)]
        public string OrigOff {
            get {
                return this.OrigOffField;
            }
            set {
                if ((object.ReferenceEquals(this.OrigOffField, value) != true)) {
                    this.OrigOffField = value;
                    this.RaisePropertyChanged("OrigOff");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=20)]
        public string FacyPolId {
            get {
                return this.FacyPolIdField;
            }
            set {
                if ((object.ReferenceEquals(this.FacyPolIdField, value) != true)) {
                    this.FacyPolIdField = value;
                    this.RaisePropertyChanged("FacyPolId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=21)]
        public string RenPolId {
            get {
                return this.RenPolIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RenPolIdField, value) != true)) {
                    this.RenPolIdField = value;
                    this.RaisePropertyChanged("RenPolId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=22)]
        public string PolId {
            get {
                return this.PolIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PolIdField, value) != true)) {
                    this.PolIdField = value;
                    this.RaisePropertyChanged("PolId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=23)]
        public string LmtCcy {
            get {
                return this.LmtCcyField;
            }
            set {
                if ((object.ReferenceEquals(this.LmtCcyField, value) != true)) {
                    this.LmtCcyField = value;
                    this.RaisePropertyChanged("LmtCcy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public System.Nullable<decimal> LmtAmt {
            get {
                return this.LmtAmtField;
            }
            set {
                if ((this.LmtAmtField.Equals(value) != true)) {
                    this.LmtAmtField = value;
                    this.RaisePropertyChanged("LmtAmt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=25)]
        public string ExsCcy {
            get {
                return this.ExsCcyField;
            }
            set {
                if ((object.ReferenceEquals(this.ExsCcyField, value) != true)) {
                    this.ExsCcyField = value;
                    this.RaisePropertyChanged("ExsCcy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public System.Nullable<decimal> ExsAmt {
            get {
                return this.ExsAmtField;
            }
            set {
                if ((this.ExsAmtField.Equals(value) != true)) {
                    this.ExsAmtField = value;
                    this.RaisePropertyChanged("ExsAmt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=27)]
        public string BindSt {
            get {
                return this.BindStField;
            }
            set {
                if ((object.ReferenceEquals(this.BindStField, value) != true)) {
                    this.BindStField = value;
                    this.RaisePropertyChanged("BindSt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=28)]
        public string PctgAmt {
            get {
                return this.PctgAmtField;
            }
            set {
                if ((object.ReferenceEquals(this.PctgAmtField, value) != true)) {
                    this.PctgAmtField = value;
                    this.RaisePropertyChanged("PctgAmt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=29)]
        public string PricingCcy {
            get {
                return this.PricingCcyField;
            }
            set {
                if ((object.ReferenceEquals(this.PricingCcyField, value) != true)) {
                    this.PricingCcyField = value;
                    this.RaisePropertyChanged("PricingCcy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=30)]
        public string Method {
            get {
                return this.MethodField;
            }
            set {
                if ((object.ReferenceEquals(this.MethodField, value) != true)) {
                    this.MethodField = value;
                    this.RaisePropertyChanged("Method");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=31)]
        public System.Nullable<decimal> TechPrm {
            get {
                return this.TechPrmField;
            }
            set {
                if ((this.TechPrmField.Equals(value) != true)) {
                    this.TechPrmField = value;
                    this.RaisePropertyChanged("TechPrm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=32)]
        public System.Nullable<decimal> BenchPrm {
            get {
                return this.BenchPrmField;
            }
            set {
                if ((this.BenchPrmField.Equals(value) != true)) {
                    this.BenchPrmField = value;
                    this.RaisePropertyChanged("BenchPrm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=33)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=34)]
        public System.Nullable<long> TimeStamp {
            get {
                return this.TimeStampField;
            }
            set {
                if ((this.TimeStampField.Equals(value) != true)) {
                    this.TimeStampField = value;
                    this.RaisePropertyChanged("TimeStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=35)]
        public string BkrPsu {
            get {
                return this.BkrPsuField;
            }
            set {
                if ((object.ReferenceEquals(this.BkrPsuField, value) != true)) {
                    this.BkrPsuField = value;
                    this.RaisePropertyChanged("BkrPsu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=36)]
        public string BkrNo {
            get {
                return this.BkrNoField;
            }
            set {
                if ((object.ReferenceEquals(this.BkrNoField, value) != true)) {
                    this.BkrNoField = value;
                    this.RaisePropertyChanged("BkrNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=37)]
        public string TechPmTy {
            get {
                return this.TechPmTyField;
            }
            set {
                if ((object.ReferenceEquals(this.TechPmTyField, value) != true)) {
                    this.TechPmTyField = value;
                    this.RaisePropertyChanged("TechPmTy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=38)]
        public string Ldr {
            get {
                return this.LdrField;
            }
            set {
                if ((object.ReferenceEquals(this.LdrField, value) != true)) {
                    this.LdrField = value;
                    this.RaisePropertyChanged("Ldr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=39)]
        public string LdrNo {
            get {
                return this.LdrNoField;
            }
            set {
                if ((object.ReferenceEquals(this.LdrNoField, value) != true)) {
                    this.LdrNoField = value;
                    this.RaisePropertyChanged("LdrNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=40)]
        public string FacyDsc {
            get {
                return this.FacyDscField;
            }
            set {
                if ((object.ReferenceEquals(this.FacyDscField, value) != true)) {
                    this.FacyDscField = value;
                    this.RaisePropertyChanged("FacyDsc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PolicyContract", Namespace="Subscribe.Service.DataContract")]
    [System.SerializableAttribute()]
    public partial class PolicyContract : Validus.Console.SubscribeService.Policy {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StandardOutput", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class StandardOutput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Validus.Console.SubscribeService.ErrorInfo ErrorInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasNotificationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MessageIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OutputXmlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Validus.Console.SubscribeService.ErrorInfo ErrorInfo {
            get {
                return this.ErrorInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorInfoField, value) != true)) {
                    this.ErrorInfoField = value;
                    this.RaisePropertyChanged("ErrorInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasNotification {
            get {
                return this.HasNotificationField;
            }
            set {
                if ((this.HasNotificationField.Equals(value) != true)) {
                    this.HasNotificationField = value;
                    this.RaisePropertyChanged("HasNotification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MessageID {
            get {
                return this.MessageIDField;
            }
            set {
                if ((this.MessageIDField.Equals(value) != true)) {
                    this.MessageIDField = value;
                    this.RaisePropertyChanged("MessageID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OutputXml {
            get {
                return this.OutputXmlField;
            }
            set {
                if ((object.ReferenceEquals(this.OutputXmlField, value) != true)) {
                    this.OutputXmlField = value;
                    this.RaisePropertyChanged("OutputXml");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorInfo", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class ErrorInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailedDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorXMLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SeverityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DetailedDescription {
            get {
                return this.DetailedDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailedDescriptionField, value) != true)) {
                    this.DetailedDescriptionField = value;
                    this.RaisePropertyChanged("DetailedDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorType {
            get {
                return this.ErrorTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorTypeField, value) != true)) {
                    this.ErrorTypeField = value;
                    this.RaisePropertyChanged("ErrorType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorXML {
            get {
                return this.ErrorXMLField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorXMLField, value) != true)) {
                    this.ErrorXMLField = value;
                    this.RaisePropertyChanged("ErrorXML");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Severity {
            get {
                return this.SeverityField;
            }
            set {
                if ((this.SeverityField.Equals(value) != true)) {
                    this.SeverityField = value;
                    this.RaisePropertyChanged("Severity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoCollection", Namespace="http://schemas.datacontract.org/2004/07/Subcribe.Services.BusinessLogic")]
    [System.SerializableAttribute()]
    public partial class InfoCollection : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NewFacyPolIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PolIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitPsuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsrNmField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewFacyPolId {
            get {
                return this.NewFacyPolIdField;
            }
            set {
                if ((object.ReferenceEquals(this.NewFacyPolIdField, value) != true)) {
                    this.NewFacyPolIdField = value;
                    this.RaisePropertyChanged("NewFacyPolId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PolId {
            get {
                return this.PolIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PolIdField, value) != true)) {
                    this.PolIdField = value;
                    this.RaisePropertyChanged("PolId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnitPsu {
            get {
                return this.UnitPsuField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitPsuField, value) != true)) {
                    this.UnitPsuField = value;
                    this.RaisePropertyChanged("UnitPsu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsrNm {
            get {
                return this.UsrNmField;
            }
            set {
                if ((object.ReferenceEquals(this.UsrNmField, value) != true)) {
                    this.UsrNmField = value;
                    this.RaisePropertyChanged("UsrNm");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SubscribeService.IPolicyService")]
    public interface IPolicyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolicyService/CreateQuote", ReplyAction="http://tempuri.org/IPolicyService/CreateQuoteResponse")]
        Validus.Console.SubscribeService.CreateQuoteResponse CreateQuote(Validus.Console.SubscribeService.CreateQuoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolicyService/CreateQuote", ReplyAction="http://tempuri.org/IPolicyService/CreateQuoteResponse")]
        System.Threading.Tasks.Task<Validus.Console.SubscribeService.CreateQuoteResponse> CreateQuoteAsync(Validus.Console.SubscribeService.CreateQuoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolicyService/UpdatePolicy", ReplyAction="http://tempuri.org/IPolicyService/UpdatePolicyResponse")]
        Validus.Console.SubscribeService.UpdatePolicyResponse UpdatePolicy(Validus.Console.SubscribeService.UpdatePolicyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolicyService/UpdatePolicy", ReplyAction="http://tempuri.org/IPolicyService/UpdatePolicyResponse")]
        System.Threading.Tasks.Task<Validus.Console.SubscribeService.UpdatePolicyResponse> UpdatePolicyAsync(Validus.Console.SubscribeService.UpdatePolicyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolicyService/GetReference", ReplyAction="http://tempuri.org/IPolicyService/GetReferenceResponse")]
        Validus.Console.SubscribeService.GetReferenceResponse GetReference(Validus.Console.SubscribeService.GetReferenceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolicyService/GetReference", ReplyAction="http://tempuri.org/IPolicyService/GetReferenceResponse")]
        System.Threading.Tasks.Task<Validus.Console.SubscribeService.GetReferenceResponse> GetReferenceAsync(Validus.Console.SubscribeService.GetReferenceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateQuote", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateQuoteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Validus.Console.SubscribeService.PolicyContract objPolicyContract;
        
        public CreateQuoteRequest() {
        }
        
        public CreateQuoteRequest(Validus.Console.SubscribeService.PolicyContract objPolicyContract) {
            this.objPolicyContract = objPolicyContract;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateQuoteResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateQuoteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Validus.Console.SubscribeService.StandardOutput CreateQuoteResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public Validus.Console.SubscribeService.InfoCollection objInfoCollection;
        
        public CreateQuoteResponse() {
        }
        
        public CreateQuoteResponse(Validus.Console.SubscribeService.StandardOutput CreateQuoteResult, Validus.Console.SubscribeService.InfoCollection objInfoCollection) {
            this.CreateQuoteResult = CreateQuoteResult;
            this.objInfoCollection = objInfoCollection;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdatePolicy", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdatePolicyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Validus.Console.SubscribeService.PolicyContract objPolicyContract;
        
        public UpdatePolicyRequest() {
        }
        
        public UpdatePolicyRequest(Validus.Console.SubscribeService.PolicyContract objPolicyContract) {
            this.objPolicyContract = objPolicyContract;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdatePolicyResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdatePolicyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Validus.Console.SubscribeService.StandardOutput UpdatePolicyResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public Validus.Console.SubscribeService.InfoCollection objInfoCollection;
        
        public UpdatePolicyResponse() {
        }
        
        public UpdatePolicyResponse(Validus.Console.SubscribeService.StandardOutput UpdatePolicyResult, Validus.Console.SubscribeService.InfoCollection objInfoCollection) {
            this.UpdatePolicyResult = UpdatePolicyResult;
            this.objInfoCollection = objInfoCollection;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetReference", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetReferenceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strPolId;
        
        public GetReferenceRequest() {
        }
        
        public GetReferenceRequest(string strPolId) {
            this.strPolId = strPolId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetReferenceResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetReferenceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Validus.Console.SubscribeService.StandardOutput GetReferenceResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public Validus.Console.SubscribeService.InfoCollection objInfoCollection;
        
        public GetReferenceResponse() {
        }
        
        public GetReferenceResponse(Validus.Console.SubscribeService.StandardOutput GetReferenceResult, Validus.Console.SubscribeService.InfoCollection objInfoCollection) {
            this.GetReferenceResult = GetReferenceResult;
            this.objInfoCollection = objInfoCollection;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPolicyServiceChannel : Validus.Console.SubscribeService.IPolicyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PolicyServiceClient : System.ServiceModel.ClientBase<Validus.Console.SubscribeService.IPolicyService>, Validus.Console.SubscribeService.IPolicyService {
        
        public PolicyServiceClient() {
        }
        
        public PolicyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PolicyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PolicyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PolicyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Validus.Console.SubscribeService.CreateQuoteResponse CreateQuote(Validus.Console.SubscribeService.CreateQuoteRequest request) {
            return base.Channel.CreateQuote(request);
        }
        
        public System.Threading.Tasks.Task<Validus.Console.SubscribeService.CreateQuoteResponse> CreateQuoteAsync(Validus.Console.SubscribeService.CreateQuoteRequest request) {
            return base.Channel.CreateQuoteAsync(request);
        }
        
        public Validus.Console.SubscribeService.UpdatePolicyResponse UpdatePolicy(Validus.Console.SubscribeService.UpdatePolicyRequest request) {
            return base.Channel.UpdatePolicy(request);
        }
        
        public System.Threading.Tasks.Task<Validus.Console.SubscribeService.UpdatePolicyResponse> UpdatePolicyAsync(Validus.Console.SubscribeService.UpdatePolicyRequest request) {
            return base.Channel.UpdatePolicyAsync(request);
        }
        
        public Validus.Console.SubscribeService.GetReferenceResponse GetReference(Validus.Console.SubscribeService.GetReferenceRequest request) {
            return base.Channel.GetReference(request);
        }
        
        public System.Threading.Tasks.Task<Validus.Console.SubscribeService.GetReferenceResponse> GetReferenceAsync(Validus.Console.SubscribeService.GetReferenceRequest request) {
            return base.Channel.GetReferenceAsync(request);
        }
    }
}
