//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18034.
// 
#pragma warning disable 1591

namespace Validus.Console.WorldCheckService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WorldCheckServiceSoap", Namespace="http://talbotuw.com/webservices/worldcheck")]
    public partial class WorldCheckService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetCountriesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCategoriesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSearchMatchesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetWorldCheckItemByUIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetIgnoreStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetItemAsSavedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllInsuredsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInsuredMatchesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPoliciesForInsuredOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetReviewedStatusForInsuredOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetInsuredAsIgnoredOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProcessMatchesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllUnmatchedInsuredsCountOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WorldCheckService() {
            this.Url = global::Validus.Console.Properties.Settings.Default.Validus_Console_WorldCheckService_WorldCheckService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetCountriesCompletedEventHandler GetCountriesCompleted;
        
        /// <remarks/>
        public event GetCategoriesCompletedEventHandler GetCategoriesCompleted;
        
        /// <remarks/>
        public event GetSearchMatchesCompletedEventHandler GetSearchMatchesCompleted;
        
        /// <remarks/>
        public event GetWorldCheckItemByUIDCompletedEventHandler GetWorldCheckItemByUIDCompleted;
        
        /// <remarks/>
        public event SetIgnoreStatusCompletedEventHandler SetIgnoreStatusCompleted;
        
        /// <remarks/>
        public event SetItemAsSavedCompletedEventHandler SetItemAsSavedCompleted;
        
        /// <remarks/>
        public event GetAllInsuredsCompletedEventHandler GetAllInsuredsCompleted;
        
        /// <remarks/>
        public event GetInsuredMatchesCompletedEventHandler GetInsuredMatchesCompleted;
        
        /// <remarks/>
        public event GetPoliciesForInsuredCompletedEventHandler GetPoliciesForInsuredCompleted;
        
        /// <remarks/>
        public event SetReviewedStatusForInsuredCompletedEventHandler SetReviewedStatusForInsuredCompleted;
        
        /// <remarks/>
        public event SetInsuredAsIgnoredCompletedEventHandler SetInsuredAsIgnoredCompleted;
        
        /// <remarks/>
        public event ProcessMatchesCompletedEventHandler ProcessMatchesCompleted;
        
        /// <remarks/>
        public event GetAllUnmatchedInsuredsCountCompletedEventHandler GetAllUnmatchedInsuredsCountCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://talbotuw.com/webservices/worldcheck/GetCountries", RequestNamespace="http://talbotuw.com/webservices/worldcheck", ResponseNamespace="http://talbotuw.com/webservices/worldcheck", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Country[] GetCountries() {
            object[] results = this.Invoke("GetCountries", new object[0]);
            return ((Country[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCountriesAsync() {
            this.GetCountriesAsync(null);
        }
        
        /// <remarks/>
        public void GetCountriesAsync(object userState) {
            if ((this.GetCountriesOperationCompleted == null)) {
                this.GetCountriesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCountriesOperationCompleted);
            }
            this.InvokeAsync("GetCountries", new object[0], this.GetCountriesOperationCompleted, userState);
        }
        
        private void OnGetCountriesOperationCompleted(object arg) {
            if ((this.GetCountriesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCountriesCompleted(this, new GetCountriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://talbotuw.com/webservices/worldcheck/GetCategories", RequestNamespace="http://talbotuw.com/webservices/worldcheck", ResponseNamespace="http://talbotuw.com/webservices/worldcheck", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Category[] GetCategories() {
            object[] results = this.Invoke("GetCategories", new object[0]);
            return ((Category[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCategoriesAsync() {
            this.GetCategoriesAsync(null);
        }
        
        /// <remarks/>
        public void GetCategoriesAsync(object userState) {
            if ((this.GetCategoriesOperationCompleted == null)) {
                this.GetCategoriesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCategoriesOperationCompleted);
            }
            this.InvokeAsync("GetCategories", new object[0], this.GetCategoriesOperationCompleted, userState);
        }
        
        private void OnGetCategoriesOperationCompleted(object arg) {
            if ((this.GetCategoriesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCategoriesCompleted(this, new GetCategoriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://talbotuw.com/webservices/worldcheck/GetSearchMatches", RequestNamespace="http://talbotuw.com/webservices/worldcheck", ResponseNamespace="http://talbotuw.com/webservices/worldcheck", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SearchResult[] GetSearchMatches(string name, string keywords, string country, string category, string uid, string username) {
            object[] results = this.Invoke("GetSearchMatches", new object[] {
                        name,
                        keywords,
                        country,
                        category,
                        uid,
                        username});
            return ((SearchResult[])(results[0]));
        }
        
        /// <remarks/>
        public void GetSearchMatchesAsync(string name, string keywords, string country, string category, string uid, string username) {
            this.GetSearchMatchesAsync(name, keywords, country, category, uid, username, null);
        }
        
        /// <remarks/>
        public void GetSearchMatchesAsync(string name, string keywords, string country, string category, string uid, string username, object userState) {
            if ((this.GetSearchMatchesOperationCompleted == null)) {
                this.GetSearchMatchesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSearchMatchesOperationCompleted);
            }
            this.InvokeAsync("GetSearchMatches", new object[] {
                        name,
                        keywords,
                        country,
                        category,
                        uid,
                        username}, this.GetSearchMatchesOperationCompleted, userState);
        }
        
        private void OnGetSearchMatchesOperationCompleted(object arg) {
            if ((this.GetSearchMatchesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSearchMatchesCompleted(this, new GetSearchMatchesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://talbotuw.com/webservices/worldcheck/GetWorldCheckItemByUID", RequestNamespace="http://talbotuw.com/webservices/worldcheck", ResponseNamespace="http://talbotuw.com/webservices/worldcheck", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WorldCheckItem GetWorldCheckItemByUID(string uid) {
            object[] results = this.Invoke("GetWorldCheckItemByUID", new object[] {
                        uid});
            return ((WorldCheckItem)(results[0]));
        }
        
        /// <remarks/>
        public void GetWorldCheckItemByUIDAsync(string uid) {
            this.GetWorldCheckItemByUIDAsync(uid, null);
        }
        
        /// <remarks/>
        public void GetWorldCheckItemByUIDAsync(string uid, object userState) {
            if ((this.GetWorldCheckItemByUIDOperationCompleted == null)) {
                this.GetWorldCheckItemByUIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWorldCheckItemByUIDOperationCompleted);
            }
            this.InvokeAsync("GetWorldCheckItemByUID", new object[] {
                        uid}, this.GetWorldCheckItemByUIDOperationCompleted, userState);
        }
        
        private void OnGetWorldCheckItemByUIDOperationCompleted(object arg) {
            if ((this.GetWorldCheckItemByUIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWorldCheckItemByUIDCompleted(this, new GetWorldCheckItemByUIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://talbotuw.com/webservices/worldcheck/SetIgnoreStatus", RequestNamespace="http://talbotuw.com/webservices/worldcheck", ResponseNamespace="http://talbotuw.com/webservices/worldcheck", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SetIgnoreStatus(string uid, bool ignored, string ignoredBy) {
            object[] results = this.Invoke("SetIgnoreStatus", new object[] {
                        uid,
                        ignored,
                        ignoredBy});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SetIgnoreStatusAsync(string uid, bool ignored, string ignoredBy) {
            this.SetIgnoreStatusAsync(uid, ignored, ignoredBy, null);
        }
        
        /// <remarks/>
        public void SetIgnoreStatusAsync(string uid, bool ignored, string ignoredBy, object userState) {
            if ((this.SetIgnoreStatusOperationCompleted == null)) {
                this.SetIgnoreStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetIgnoreStatusOperationCompleted);
            }
            this.InvokeAsync("SetIgnoreStatus", new object[] {
                        uid,
                        ignored,
                        ignoredBy}, this.SetIgnoreStatusOperationCompleted, userState);
        }
        
        private void OnSetIgnoreStatusOperationCompleted(object arg) {
            if ((this.SetIgnoreStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetIgnoreStatusCompleted(this, new SetIgnoreStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://talbotuw.com/webservices/worldcheck/SetItemAsSaved", RequestNamespace="http://talbotuw.com/webservices/worldcheck", ResponseNamespace="http://talbotuw.com/webservices/worldcheck", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SetItemAsSaved(string uid, string userName, string polId) {
            object[] results = this.Invoke("SetItemAsSaved", new object[] {
                        uid,
                        userName,
                        polId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SetItemAsSavedAsync(string uid, string userName, string polId) {
            this.SetItemAsSavedAsync(uid, userName, polId, null);
        }
        
        /// <remarks/>
        public void SetItemAsSavedAsync(string uid, string userName, string polId, object userState) {
            if ((this.SetItemAsSavedOperationCompleted == null)) {
                this.SetItemAsSavedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetItemAsSavedOperationCompleted);
            }
            this.InvokeAsync("SetItemAsSaved", new object[] {
                        uid,
                        userName,
                        polId}, this.SetItemAsSavedOperationCompleted, userState);
        }
        
        private void OnSetItemAsSavedOperationCompleted(object arg) {
            if ((this.SetItemAsSavedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetItemAsSavedCompleted(this, new SetItemAsSavedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://talbotuw.com/webservices/worldcheck/GetAllInsureds", RequestNamespace="http://talbotuw.com/webservices/worldcheck", ResponseNamespace="http://talbotuw.com/webservices/worldcheck", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AutomaticSearchMatches[] GetAllInsureds(bool showIgnored, string source, string filter) {
            object[] results = this.Invoke("GetAllInsureds", new object[] {
                        showIgnored,
                        source,
                        filter});
            return ((AutomaticSearchMatches[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllInsuredsAsync(bool showIgnored, string source, string filter) {
            this.GetAllInsuredsAsync(showIgnored, source, filter, null);
        }
        
        /// <remarks/>
        public void GetAllInsuredsAsync(bool showIgnored, string source, string filter, object userState) {
            if ((this.GetAllInsuredsOperationCompleted == null)) {
                this.GetAllInsuredsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllInsuredsOperationCompleted);
            }
            this.InvokeAsync("GetAllInsureds", new object[] {
                        showIgnored,
                        source,
                        filter}, this.GetAllInsuredsOperationCompleted, userState);
        }
        
        private void OnGetAllInsuredsOperationCompleted(object arg) {
            if ((this.GetAllInsuredsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllInsuredsCompleted(this, new GetAllInsuredsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://talbotuw.com/webservices/worldcheck/GetInsuredMatches", RequestNamespace="http://talbotuw.com/webservices/worldcheck", ResponseNamespace="http://talbotuw.com/webservices/worldcheck", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WorldCheckItem[] GetInsuredMatches(bool showIgnored, string source, string insuredName) {
            object[] results = this.Invoke("GetInsuredMatches", new object[] {
                        showIgnored,
                        source,
                        insuredName});
            return ((WorldCheckItem[])(results[0]));
        }
        
        /// <remarks/>
        public void GetInsuredMatchesAsync(bool showIgnored, string source, string insuredName) {
            this.GetInsuredMatchesAsync(showIgnored, source, insuredName, null);
        }
        
        /// <remarks/>
        public void GetInsuredMatchesAsync(bool showIgnored, string source, string insuredName, object userState) {
            if ((this.GetInsuredMatchesOperationCompleted == null)) {
                this.GetInsuredMatchesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInsuredMatchesOperationCompleted);
            }
            this.InvokeAsync("GetInsuredMatches", new object[] {
                        showIgnored,
                        source,
                        insuredName}, this.GetInsuredMatchesOperationCompleted, userState);
        }
        
        private void OnGetInsuredMatchesOperationCompleted(object arg) {
            if ((this.GetInsuredMatchesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInsuredMatchesCompleted(this, new GetInsuredMatchesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://talbotuw.com/webservices/worldcheck/GetPoliciesForInsured", RequestNamespace="http://talbotuw.com/webservices/worldcheck", ResponseNamespace="http://talbotuw.com/webservices/worldcheck", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Policy[] GetPoliciesForInsured(string insuredName, string source) {
            object[] results = this.Invoke("GetPoliciesForInsured", new object[] {
                        insuredName,
                        source});
            return ((Policy[])(results[0]));
        }
        
        /// <remarks/>
        public void GetPoliciesForInsuredAsync(string insuredName, string source) {
            this.GetPoliciesForInsuredAsync(insuredName, source, null);
        }
        
        /// <remarks/>
        public void GetPoliciesForInsuredAsync(string insuredName, string source, object userState) {
            if ((this.GetPoliciesForInsuredOperationCompleted == null)) {
                this.GetPoliciesForInsuredOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPoliciesForInsuredOperationCompleted);
            }
            this.InvokeAsync("GetPoliciesForInsured", new object[] {
                        insuredName,
                        source}, this.GetPoliciesForInsuredOperationCompleted, userState);
        }
        
        private void OnGetPoliciesForInsuredOperationCompleted(object arg) {
            if ((this.GetPoliciesForInsuredCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPoliciesForInsuredCompleted(this, new GetPoliciesForInsuredCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://talbotuw.com/webservices/worldcheck/SetReviewedStatusForInsured", RequestNamespace="http://talbotuw.com/webservices/worldcheck", ResponseNamespace="http://talbotuw.com/webservices/worldcheck", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SetReviewedStatusForInsured(int UID, string insuredName, bool reviewed, string source, string userName) {
            object[] results = this.Invoke("SetReviewedStatusForInsured", new object[] {
                        UID,
                        insuredName,
                        reviewed,
                        source,
                        userName});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SetReviewedStatusForInsuredAsync(int UID, string insuredName, bool reviewed, string source, string userName) {
            this.SetReviewedStatusForInsuredAsync(UID, insuredName, reviewed, source, userName, null);
        }
        
        /// <remarks/>
        public void SetReviewedStatusForInsuredAsync(int UID, string insuredName, bool reviewed, string source, string userName, object userState) {
            if ((this.SetReviewedStatusForInsuredOperationCompleted == null)) {
                this.SetReviewedStatusForInsuredOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetReviewedStatusForInsuredOperationCompleted);
            }
            this.InvokeAsync("SetReviewedStatusForInsured", new object[] {
                        UID,
                        insuredName,
                        reviewed,
                        source,
                        userName}, this.SetReviewedStatusForInsuredOperationCompleted, userState);
        }
        
        private void OnSetReviewedStatusForInsuredOperationCompleted(object arg) {
            if ((this.SetReviewedStatusForInsuredCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetReviewedStatusForInsuredCompleted(this, new SetReviewedStatusForInsuredCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://talbotuw.com/webservices/worldcheck/SetInsuredAsIgnored", RequestNamespace="http://talbotuw.com/webservices/worldcheck", ResponseNamespace="http://talbotuw.com/webservices/worldcheck", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SetInsuredAsIgnored(string insuredName, string source) {
            object[] results = this.Invoke("SetInsuredAsIgnored", new object[] {
                        insuredName,
                        source});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SetInsuredAsIgnoredAsync(string insuredName, string source) {
            this.SetInsuredAsIgnoredAsync(insuredName, source, null);
        }
        
        /// <remarks/>
        public void SetInsuredAsIgnoredAsync(string insuredName, string source, object userState) {
            if ((this.SetInsuredAsIgnoredOperationCompleted == null)) {
                this.SetInsuredAsIgnoredOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetInsuredAsIgnoredOperationCompleted);
            }
            this.InvokeAsync("SetInsuredAsIgnored", new object[] {
                        insuredName,
                        source}, this.SetInsuredAsIgnoredOperationCompleted, userState);
        }
        
        private void OnSetInsuredAsIgnoredOperationCompleted(object arg) {
            if ((this.SetInsuredAsIgnoredCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetInsuredAsIgnoredCompleted(this, new SetInsuredAsIgnoredCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://talbotuw.com/webservices/worldcheck/ProcessMatches", RequestNamespace="http://talbotuw.com/webservices/worldcheck", ResponseNamespace="http://talbotuw.com/webservices/worldcheck", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ProcessMatches() {
            object[] results = this.Invoke("ProcessMatches", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ProcessMatchesAsync() {
            this.ProcessMatchesAsync(null);
        }
        
        /// <remarks/>
        public void ProcessMatchesAsync(object userState) {
            if ((this.ProcessMatchesOperationCompleted == null)) {
                this.ProcessMatchesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcessMatchesOperationCompleted);
            }
            this.InvokeAsync("ProcessMatches", new object[0], this.ProcessMatchesOperationCompleted, userState);
        }
        
        private void OnProcessMatchesOperationCompleted(object arg) {
            if ((this.ProcessMatchesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcessMatchesCompleted(this, new ProcessMatchesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://talbotuw.com/webservices/worldcheck/GetAllUnmatchedInsuredsCount", RequestNamespace="http://talbotuw.com/webservices/worldcheck", ResponseNamespace="http://talbotuw.com/webservices/worldcheck", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetAllUnmatchedInsuredsCount(string source) {
            object[] results = this.Invoke("GetAllUnmatchedInsuredsCount", new object[] {
                        source});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllUnmatchedInsuredsCountAsync(string source) {
            this.GetAllUnmatchedInsuredsCountAsync(source, null);
        }
        
        /// <remarks/>
        public void GetAllUnmatchedInsuredsCountAsync(string source, object userState) {
            if ((this.GetAllUnmatchedInsuredsCountOperationCompleted == null)) {
                this.GetAllUnmatchedInsuredsCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllUnmatchedInsuredsCountOperationCompleted);
            }
            this.InvokeAsync("GetAllUnmatchedInsuredsCount", new object[] {
                        source}, this.GetAllUnmatchedInsuredsCountOperationCompleted, userState);
        }
        
        private void OnGetAllUnmatchedInsuredsCountOperationCompleted(object arg) {
            if ((this.GetAllUnmatchedInsuredsCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllUnmatchedInsuredsCountCompleted(this, new GetAllUnmatchedInsuredsCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://talbotuw.com/webservices/worldcheck")]
    public partial class Country {
        
        private string nameField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://talbotuw.com/webservices/worldcheck")]
    public partial class Policy {
        
        private string vPolicyKeyField;
        
        private string vInsuredKeyField;
        
        private string policyReferenceField;
        
        private string accountYearField;
        
        private string policyDescriptionField;
        
        private string policyNotesField;
        
        private string relatedInsuredsField;
        
        private System.DateTime coverStartDateField;
        
        private System.DateTime coverEndDateField;
        
        private string underwriterField;
        
        private string writtenDateField;
        
        private string sourceDatabaseField;
        
        private string originatingOfficeField;
        
        private string validFromDateField;
        
        private string geoCdField;
        
        private string domicileCountryField;
        
        /// <remarks/>
        public string VPolicyKey {
            get {
                return this.vPolicyKeyField;
            }
            set {
                this.vPolicyKeyField = value;
            }
        }
        
        /// <remarks/>
        public string VInsuredKey {
            get {
                return this.vInsuredKeyField;
            }
            set {
                this.vInsuredKeyField = value;
            }
        }
        
        /// <remarks/>
        public string PolicyReference {
            get {
                return this.policyReferenceField;
            }
            set {
                this.policyReferenceField = value;
            }
        }
        
        /// <remarks/>
        public string AccountYear {
            get {
                return this.accountYearField;
            }
            set {
                this.accountYearField = value;
            }
        }
        
        /// <remarks/>
        public string PolicyDescription {
            get {
                return this.policyDescriptionField;
            }
            set {
                this.policyDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string PolicyNotes {
            get {
                return this.policyNotesField;
            }
            set {
                this.policyNotesField = value;
            }
        }
        
        /// <remarks/>
        public string RelatedInsureds {
            get {
                return this.relatedInsuredsField;
            }
            set {
                this.relatedInsuredsField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CoverStartDate {
            get {
                return this.coverStartDateField;
            }
            set {
                this.coverStartDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CoverEndDate {
            get {
                return this.coverEndDateField;
            }
            set {
                this.coverEndDateField = value;
            }
        }
        
        /// <remarks/>
        public string Underwriter {
            get {
                return this.underwriterField;
            }
            set {
                this.underwriterField = value;
            }
        }
        
        /// <remarks/>
        public string WrittenDate {
            get {
                return this.writtenDateField;
            }
            set {
                this.writtenDateField = value;
            }
        }
        
        /// <remarks/>
        public string SourceDatabase {
            get {
                return this.sourceDatabaseField;
            }
            set {
                this.sourceDatabaseField = value;
            }
        }
        
        /// <remarks/>
        public string OriginatingOffice {
            get {
                return this.originatingOfficeField;
            }
            set {
                this.originatingOfficeField = value;
            }
        }
        
        /// <remarks/>
        public string ValidFromDate {
            get {
                return this.validFromDateField;
            }
            set {
                this.validFromDateField = value;
            }
        }
        
        /// <remarks/>
        public string GeoCd {
            get {
                return this.geoCdField;
            }
            set {
                this.geoCdField = value;
            }
        }
        
        /// <remarks/>
        public string DomicileCountry {
            get {
                return this.domicileCountryField;
            }
            set {
                this.domicileCountryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://talbotuw.com/webservices/worldcheck")]
    public partial class Insured {
        
        private string vInsuredKeyField;
        
        private string insuredIdField;
        
        private string insuredNameField;
        
        private string firstNameField;
        
        private string relatedNamesField;
        
        private string sourceDatabaseField;
        
        private string originatingOfficeField;
        
        private string validFromDateField;
        
        private bool flaggedMatchField;
        
        private bool ingorneFlaggedMatchField;
        
        /// <remarks/>
        public string vInsuredKey {
            get {
                return this.vInsuredKeyField;
            }
            set {
                this.vInsuredKeyField = value;
            }
        }
        
        /// <remarks/>
        public string InsuredId {
            get {
                return this.insuredIdField;
            }
            set {
                this.insuredIdField = value;
            }
        }
        
        /// <remarks/>
        public string InsuredName {
            get {
                return this.insuredNameField;
            }
            set {
                this.insuredNameField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string RelatedNames {
            get {
                return this.relatedNamesField;
            }
            set {
                this.relatedNamesField = value;
            }
        }
        
        /// <remarks/>
        public string SourceDatabase {
            get {
                return this.sourceDatabaseField;
            }
            set {
                this.sourceDatabaseField = value;
            }
        }
        
        /// <remarks/>
        public string OriginatingOffice {
            get {
                return this.originatingOfficeField;
            }
            set {
                this.originatingOfficeField = value;
            }
        }
        
        /// <remarks/>
        public string ValidFromDate {
            get {
                return this.validFromDateField;
            }
            set {
                this.validFromDateField = value;
            }
        }
        
        /// <remarks/>
        public bool FlaggedMatch {
            get {
                return this.flaggedMatchField;
            }
            set {
                this.flaggedMatchField = value;
            }
        }
        
        /// <remarks/>
        public bool IngorneFlaggedMatch {
            get {
                return this.ingorneFlaggedMatchField;
            }
            set {
                this.ingorneFlaggedMatchField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://talbotuw.com/webservices/worldcheck")]
    public partial class AutomaticSearchMatches {
        
        private int reviewFlagField;
        
        private int matchCountField;
        
        private System.DateTime matchDateField;
        
        private Insured insuredField;
        
        /// <remarks/>
        public int ReviewFlag {
            get {
                return this.reviewFlagField;
            }
            set {
                this.reviewFlagField = value;
            }
        }
        
        /// <remarks/>
        public int MatchCount {
            get {
                return this.matchCountField;
            }
            set {
                this.matchCountField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime MatchDate {
            get {
                return this.matchDateField;
            }
            set {
                this.matchDateField = value;
            }
        }
        
        /// <remarks/>
        public Insured Insured {
            get {
                return this.insuredField;
            }
            set {
                this.insuredField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://talbotuw.com/webservices/worldcheck")]
    public partial class WorldCheckInfoItem {
        
        private string headerField;
        
        private string bodyField;
        
        /// <remarks/>
        public string Header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
            }
        }
        
        /// <remarks/>
        public string Body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://talbotuw.com/webservices/worldcheck")]
    public partial class WorldCheckItem {
        
        private int uIDField;
        
        private string lastNameField;
        
        private string firstNameField;
        
        private string aliasesField;
        
        private string[] aliasesListField;
        
        private string alternativeSpellingField;
        
        private string[] alternativeSpellingListField;
        
        private string colourField;
        
        private string categoryField;
        
        private string subCategoryField;
        
        private string titleField;
        
        private string positionField;
        
        private int ageField;
        
        private string dOBField;
        
        private string placeOfBirthField;
        
        private string deceasedField;
        
        private string passportsField;
        
        private string sSNField;
        
        private string locationsField;
        
        private string[] locationsListField;
        
        private string countryField;
        
        private string companiesField;
        
        private string[] companiesListField;
        
        private string linkedToField;
        
        private string[] linkedToListField;
        
        private string furtherInformationField;
        
        private string keywordsField;
        
        private string[] keywordsListField;
        
        private string externalSourcesField;
        
        private string[] externalSourcesListField;
        
        private string enteredField;
        
        private string updatedField;
        
        private string e_iField;
        
        private bool ignoredField;
        
        private bool reviewedField;
        
        private bool manualMatchField;
        
        private WorldCheckInfoItem[] furtherInformationListField;
        
        /// <remarks/>
        public int UID {
            get {
                return this.uIDField;
            }
            set {
                this.uIDField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string Aliases {
            get {
                return this.aliasesField;
            }
            set {
                this.aliasesField = value;
            }
        }
        
        /// <remarks/>
        public string[] AliasesList {
            get {
                return this.aliasesListField;
            }
            set {
                this.aliasesListField = value;
            }
        }
        
        /// <remarks/>
        public string AlternativeSpelling {
            get {
                return this.alternativeSpellingField;
            }
            set {
                this.alternativeSpellingField = value;
            }
        }
        
        /// <remarks/>
        public string[] AlternativeSpellingList {
            get {
                return this.alternativeSpellingListField;
            }
            set {
                this.alternativeSpellingListField = value;
            }
        }
        
        /// <remarks/>
        public string colour {
            get {
                return this.colourField;
            }
            set {
                this.colourField = value;
            }
        }
        
        /// <remarks/>
        public string Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        public string SubCategory {
            get {
                return this.subCategoryField;
            }
            set {
                this.subCategoryField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        public int Age {
            get {
                return this.ageField;
            }
            set {
                this.ageField = value;
            }
        }
        
        /// <remarks/>
        public string DOB {
            get {
                return this.dOBField;
            }
            set {
                this.dOBField = value;
            }
        }
        
        /// <remarks/>
        public string PlaceOfBirth {
            get {
                return this.placeOfBirthField;
            }
            set {
                this.placeOfBirthField = value;
            }
        }
        
        /// <remarks/>
        public string Deceased {
            get {
                return this.deceasedField;
            }
            set {
                this.deceasedField = value;
            }
        }
        
        /// <remarks/>
        public string Passports {
            get {
                return this.passportsField;
            }
            set {
                this.passportsField = value;
            }
        }
        
        /// <remarks/>
        public string SSN {
            get {
                return this.sSNField;
            }
            set {
                this.sSNField = value;
            }
        }
        
        /// <remarks/>
        public string Locations {
            get {
                return this.locationsField;
            }
            set {
                this.locationsField = value;
            }
        }
        
        /// <remarks/>
        public string[] LocationsList {
            get {
                return this.locationsListField;
            }
            set {
                this.locationsListField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string Companies {
            get {
                return this.companiesField;
            }
            set {
                this.companiesField = value;
            }
        }
        
        /// <remarks/>
        public string[] CompaniesList {
            get {
                return this.companiesListField;
            }
            set {
                this.companiesListField = value;
            }
        }
        
        /// <remarks/>
        public string LinkedTo {
            get {
                return this.linkedToField;
            }
            set {
                this.linkedToField = value;
            }
        }
        
        /// <remarks/>
        public string[] LinkedToList {
            get {
                return this.linkedToListField;
            }
            set {
                this.linkedToListField = value;
            }
        }
        
        /// <remarks/>
        public string FurtherInformation {
            get {
                return this.furtherInformationField;
            }
            set {
                this.furtherInformationField = value;
            }
        }
        
        /// <remarks/>
        public string Keywords {
            get {
                return this.keywordsField;
            }
            set {
                this.keywordsField = value;
            }
        }
        
        /// <remarks/>
        public string[] KeywordsList {
            get {
                return this.keywordsListField;
            }
            set {
                this.keywordsListField = value;
            }
        }
        
        /// <remarks/>
        public string ExternalSources {
            get {
                return this.externalSourcesField;
            }
            set {
                this.externalSourcesField = value;
            }
        }
        
        /// <remarks/>
        public string[] ExternalSourcesList {
            get {
                return this.externalSourcesListField;
            }
            set {
                this.externalSourcesListField = value;
            }
        }
        
        /// <remarks/>
        public string Entered {
            get {
                return this.enteredField;
            }
            set {
                this.enteredField = value;
            }
        }
        
        /// <remarks/>
        public string Updated {
            get {
                return this.updatedField;
            }
            set {
                this.updatedField = value;
            }
        }
        
        /// <remarks/>
        public string E_i {
            get {
                return this.e_iField;
            }
            set {
                this.e_iField = value;
            }
        }
        
        /// <remarks/>
        public bool Ignored {
            get {
                return this.ignoredField;
            }
            set {
                this.ignoredField = value;
            }
        }
        
        /// <remarks/>
        public bool Reviewed {
            get {
                return this.reviewedField;
            }
            set {
                this.reviewedField = value;
            }
        }
        
        /// <remarks/>
        public bool ManualMatch {
            get {
                return this.manualMatchField;
            }
            set {
                this.manualMatchField = value;
            }
        }
        
        /// <remarks/>
        public WorldCheckInfoItem[] FurtherInformationList {
            get {
                return this.furtherInformationListField;
            }
            set {
                this.furtherInformationListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://talbotuw.com/webservices/worldcheck")]
    public partial class SearchResult {
        
        private string lastNameField;
        
        private string firstNameField;
        
        private string countryField;
        
        private string categoryField;
        
        private int uIDField;
        
        private bool sanctionedField;
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        public int UID {
            get {
                return this.uIDField;
            }
            set {
                this.uIDField = value;
            }
        }
        
        /// <remarks/>
        public bool Sanctioned {
            get {
                return this.sanctionedField;
            }
            set {
                this.sanctionedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://talbotuw.com/webservices/worldcheck")]
    public partial class Category {
        
        private string nameField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetCountriesCompletedEventHandler(object sender, GetCountriesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCountriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCountriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Country[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Country[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetCategoriesCompletedEventHandler(object sender, GetCategoriesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCategoriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCategoriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Category[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Category[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetSearchMatchesCompletedEventHandler(object sender, GetSearchMatchesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSearchMatchesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSearchMatchesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SearchResult[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SearchResult[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetWorldCheckItemByUIDCompletedEventHandler(object sender, GetWorldCheckItemByUIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWorldCheckItemByUIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetWorldCheckItemByUIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WorldCheckItem Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WorldCheckItem)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SetIgnoreStatusCompletedEventHandler(object sender, SetIgnoreStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetIgnoreStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetIgnoreStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SetItemAsSavedCompletedEventHandler(object sender, SetItemAsSavedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetItemAsSavedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetItemAsSavedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetAllInsuredsCompletedEventHandler(object sender, GetAllInsuredsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllInsuredsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllInsuredsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AutomaticSearchMatches[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AutomaticSearchMatches[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetInsuredMatchesCompletedEventHandler(object sender, GetInsuredMatchesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInsuredMatchesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInsuredMatchesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WorldCheckItem[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WorldCheckItem[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetPoliciesForInsuredCompletedEventHandler(object sender, GetPoliciesForInsuredCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPoliciesForInsuredCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPoliciesForInsuredCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Policy[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Policy[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SetReviewedStatusForInsuredCompletedEventHandler(object sender, SetReviewedStatusForInsuredCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetReviewedStatusForInsuredCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetReviewedStatusForInsuredCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SetInsuredAsIgnoredCompletedEventHandler(object sender, SetInsuredAsIgnoredCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetInsuredAsIgnoredCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetInsuredAsIgnoredCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ProcessMatchesCompletedEventHandler(object sender, ProcessMatchesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcessMatchesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProcessMatchesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetAllUnmatchedInsuredsCountCompletedEventHandler(object sender, GetAllUnmatchedInsuredsCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllUnmatchedInsuredsCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllUnmatchedInsuredsCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591